name: subtrack_backend
channels:
  - conda-forge
  #- anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - apispec=6.6.1
  - blinker=1.6.2
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - cachecontrol=0.14.0
  - cachetools=5.5.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - expat=2.6.3
  - flask=3.0.3
  - flask-jwt-extended=4.6.0
  - flask-smorest=0.44.0
  - google-api-core=2.20.0
  - google-api-python-client=2.147.0
  - google-auth=2.35.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-firestore=2.19.0
  - google-cloud-storage=2.18.2
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.65.0
  - httplib2=0.22.0
  - idna=3.10
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.3
  - marshmallow=3.22.0
  - ncurses=6.4
  - packaging=24.1
  - pip=24.2
  - proto-plus=1.24.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pycparser=2.22
  - pyjwt=2.9.0
  - pyparsing=3.1.4
  - python=3.12.5
  - readline=8.2
  - requests=2.32.3
  - rsa=4.9
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - webargs=8.6.0
  - werkzeug=3.0.3
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - flask-cors
